export const PATH_SESSIONS_PASSWORD = '/sessions/password'
export const PATH_USERS = '/users'
export const PATH_PROFILE = '/profile'
export const PATH_PASSWORD_RECOVER = '/password/recover'
export const PATH_PASSWORD_RESET = '/password/reset'
